Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  author: "Raphael Javaux"
  authorMail: "raphaeljavaux[at]gmail.com"
  uploadDir: "files"
  maxFileSize: 157286400 # 150 Mio
  maxFiles: 15 # Used to limit the request size
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  <<: *defaults
