Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://127.0.0.1:3000"
  author: "Raphael Javaux"
  authorMail: "raphaeljavaux[at]gmail.com"
  uploadDir: "files"
  maxFileSize: 157286400 # 150 MiB
  maxRequestSize: 10485760 # 10 MiB
  maxDailyUploads: 500 # 300 uploads per ip per day
  maxDailySize: 3221225472 # 3 Gio per ip per day
  timeout: 120 # Web server timeout in seconds
  jobsThreads: 1 # Number of threads which executes background tasks
  facebook: "124047527761820" # Facebook App ID
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  <<: *defaults
