Default: &defaults
  database: getwebb.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: getwebb_test.sqlite3
  <<: *defaults

Staging:
  database: getwebb_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: getwebb_production.sqlite3
  poolsize: 100
  <<: *defaults
